/*
 * HumanControlFields.cpp
 *
 *  Created on: 21 Jan 2019
 *      Author: zal
 */

#include <dragonRfl/classes/HumanControlFields.h>

namespace dragonRfl
{

    HumanControlFields::HumanControlFields()
    : rightWeaponChannel(0)
    , leftWeaponChannel(0)
    , torsoChannel(0)
    , lowerBodyChan(0)
    , rightArmChan(0)
    , solveToChans({})
    , leftLegChans({})
    , rightLegChans({})
    , hair1Channel(0)
    , multiplayerSpeedScaling(1.0)
    , fallStartDmgSpeed(4.0)
    , fallDeathSpeed(7.0)
    , drown(odDb::AssetRef::NULL_REF)
    , drownSound(odDb::AssetRef::NULL_REF)
    , combatIdleOneHand(odDb::AssetRef::NULL_REF)
    , combatIdleTwoHand(odDb::AssetRef::NULL_REF)
    , walkOneHanded(odDb::AssetRef::NULL_REF)
    , runOneHanded(odDb::AssetRef::NULL_REF)
    , strafeLeftOneHanded(odDb::AssetRef::NULL_REF)
    , strafeRightOneHanded(odDb::AssetRef::NULL_REF)
    , walkCombat(odDb::AssetRef::NULL_REF)
    , runCombat(odDb::AssetRef::NULL_REF)
    , rideAir(odDb::AssetRef::NULL_REF)
    , rideGround(odDb::AssetRef::NULL_REF)
    , mount(odDb::AssetRef::NULL_REF)
    , dismount(odDb::AssetRef::NULL_REF)
    , jump(odDb::AssetRef::NULL_REF)
    , inAir(odDb::AssetRef::NULL_REF)
    , landing(odDb::AssetRef::NULL_REF)
    , landingSmall(odDb::AssetRef::NULL_REF)
    , landingRun(odDb::AssetRef::NULL_REF)
    , noncombatToCrouch(odDb::AssetRef::NULL_REF)
    , combatToCrouch(odDb::AssetRef::NULL_REF)
    , noncombatCrouched(odDb::AssetRef::NULL_REF)
    , combatCrouched(odDb::AssetRef::NULL_REF)
    , waddleForward(odDb::AssetRef::NULL_REF)
    , rollLeft(odDb::AssetRef::NULL_REF)
    , rollRight(odDb::AssetRef::NULL_REF)
    , rollForward(odDb::AssetRef::NULL_REF)
    , rollBack(odDb::AssetRef::NULL_REF)
    , cartwheelL(odDb::AssetRef::NULL_REF)
    , cartwheelR(odDb::AssetRef::NULL_REF)
    , flipForward(odDb::AssetRef::NULL_REF)
    , flipBack(odDb::AssetRef::NULL_REF)
    , pushRollable(odDb::AssetRef::NULL_REF)
    , pushSlidable(odDb::AssetRef::NULL_REF)
    , ladderUp1(odDb::AssetRef::NULL_REF)
    , ladderUp2(odDb::AssetRef::NULL_REF)
    , ladderDown1(odDb::AssetRef::NULL_REF)
    , ladderDown2(odDb::AssetRef::NULL_REF)
    , ladderUpLIdle(odDb::AssetRef::NULL_REF)
    , ladderUpRIdle(odDb::AssetRef::NULL_REF)
    , ladderDownRIdle(odDb::AssetRef::NULL_REF)
    , getOnLadderB(odDb::AssetRef::NULL_REF)
    , getOffLadderB(odDb::AssetRef::NULL_REF)
    , getOnLadderT(odDb::AssetRef::NULL_REF)
    , getOffLadderT(odDb::AssetRef::NULL_REF)
    , stairsUp(odDb::AssetRef::NULL_REF)
    , stairsDown(odDb::AssetRef::NULL_REF)
    , stairsUpIdleL(odDb::AssetRef::NULL_REF)
    , stairsUpIdleR(odDb::AssetRef::NULL_REF)
    , stairsDownIdleL(odDb::AssetRef::NULL_REF)
    , stairsDownIdleR(odDb::AssetRef::NULL_REF)
    , huh(odDb::AssetRef::NULL_REF)
    , _180Turn(odDb::AssetRef::NULL_REF)
    , useMagicCrystal(odDb::AssetRef::NULL_REF)
    , slideForward(odDb::AssetRef::NULL_REF)
    , slideBackward(odDb::AssetRef::NULL_REF)
    , balancing(odDb::AssetRef::NULL_REF)
    , throw(odDb::AssetRef::NULL_REF)
    , shootGun(odDb::AssetRef::NULL_REF)
    , reloadGun(odDb::AssetRef::NULL_REF)
    , archerMedium(odDb::AssetRef::NULL_REF)
    , archerLow(odDb::AssetRef::NULL_REF)
    , gunCamHorzDistance(1024.0)
    , gunCamVertDistance(1024.0)
    , oneHandRH(odDb::AssetRef::NULL_REF)
    , oneHandRM1(odDb::AssetRef::NULL_REF)
    , oneHandRM2(odDb::AssetRef::NULL_REF)
    , oneHandRM3(odDb::AssetRef::NULL_REF)
    , oneHandRL(odDb::AssetRef::NULL_REF)
    , oneHandSH(odDb::AssetRef::NULL_REF)
    , oneHandSM(odDb::AssetRef::NULL_REF)
    , oneHandSL(odDb::AssetRef::NULL_REF)
    , oneHandUB1(odDb::AssetRef::NULL_REF)
    , oneHandUB2(odDb::AssetRef::NULL_REF)
    , oneHandUB3(odDb::AssetRef::NULL_REF)
    , twoHandRH(odDb::AssetRef::NULL_REF)
    , twoHandRM1(odDb::AssetRef::NULL_REF)
    , twoHandRM2(odDb::AssetRef::NULL_REF)
    , twoHandRM3(odDb::AssetRef::NULL_REF)
    , twoHandRL(odDb::AssetRef::NULL_REF)
    , twoHandSH(odDb::AssetRef::NULL_REF)
    , twoHandSM(odDb::AssetRef::NULL_REF)
    , twoHandSL(odDb::AssetRef::NULL_REF)
    , twoHandUB1(odDb::AssetRef::NULL_REF)
    , twoHandUB2(odDb::AssetRef::NULL_REF)
    , twoHandUB3(odDb::AssetRef::NULL_REF)
    , fireSA(odDb::AssetRef::NULL_REF)
    , iceSA(odDb::AssetRef::NULL_REF)
    , lightningSA(odDb::AssetRef::NULL_REF)
    , deathSA(odDb::AssetRef::NULL_REF)
    , strafeAttackLUB(odDb::AssetRef::NULL_REF)
    , strafeAttackRUB(odDb::AssetRef::NULL_REF)
    , rollLAttack(odDb::AssetRef::NULL_REF)
    , rollRAttack(odDb::AssetRef::NULL_REF)
    , specialAttackThrust(odDb::AssetRef::NULL_REF)
    , specialAttackLeft(odDb::AssetRef::NULL_REF)
    , specialAttackRight(odDb::AssetRef::NULL_REF)
    , specialAttackSpin(odDb::AssetRef::NULL_REF)
    , specialAttackSwing180(odDb::AssetRef::NULL_REF)
    , specialAttackJump(odDb::AssetRef::NULL_REF)
    , saThrustDamageMultiplier(1.25)
    , saLeftDamageMultiplier(1.25)
    , saRightDamageMultiplier(1.25)
    , saSpinDamageMultiplier(1.25)
    , saSwing180DamageMultiplier(1.25)
    , saJumpDamageMultiplier(1.25)
    , block(odDb::AssetRef::NULL_REF)
    , crouchedBlock(odDb::AssetRef::NULL_REF)
    , blockDamageReductionPercent(25)
    , sheathe(odDb::AssetRef::NULL_REF)
    , unsheathe(odDb::AssetRef::NULL_REF)
    , reAttackWindow(0.2)
    , hitRxnHSLAnim(odDb::AssetRef::NULL_REF)
    , hitRxnHSHAnim(odDb::AssetRef::NULL_REF)
    , hitRxnOSLAnim(odDb::AssetRef::NULL_REF)
    , hitRxnOSHAnim(odDb::AssetRef::NULL_REF)
    , hitRxnFSLAnim(odDb::AssetRef::NULL_REF)
    , hitRxnFSHAnim(odDb::AssetRef::NULL_REF)
    , hitRxnHSLSound({})
    , hitRxnHSHSound({})
    , hitRxnOSLSound({})
    , hitRxnOSHSound({})
    , hitRxnFSLSound({})
    , hitRxnFSHSound({})
    , walkStrafeL(odDb::AssetRef::NULL_REF)
    , walkStrafeR(odDb::AssetRef::NULL_REF)
    , slowWalk(odDb::AssetRef::NULL_REF)
    , runBackwards(odDb::AssetRef::NULL_REF)
    , runBackwardsOneHanded(odDb::AssetRef::NULL_REF)
    , noncombat2Run(odDb::AssetRef::NULL_REF)
    , run2Ready(odDb::AssetRef::NULL_REF)
    , run2ReadyL(odDb::AssetRef::NULL_REF)
    , walk2Ready(odDb::AssetRef::NULL_REF)
    , strafeL2Ready(odDb::AssetRef::NULL_REF)
    , strafeR2Ready(odDb::AssetRef::NULL_REF)
    , turnLeft(odDb::AssetRef::NULL_REF)
    , turnRight(odDb::AssetRef::NULL_REF)
    , bumpIntoWall(odDb::AssetRef::NULL_REF)
    , swimForwardSpeed(1.2)
    , swimBackwardSpeed(-0.7)
    , airConsumptionRate(2.0)
    , airReplenishmentRate(2.0)
    , inAirToSwanDive(odDb::AssetRef::NULL_REF)
    , swanDive(odDb::AssetRef::NULL_REF)
    , swim(odDb::AssetRef::NULL_REF)
    , backswim(odDb::AssetRef::NULL_REF)
    , swimToBackswim(odDb::AssetRef::NULL_REF)
    , backswimToSwim(odDb::AssetRef::NULL_REF)
    , treadWater(odDb::AssetRef::NULL_REF)
    , idleUnderwater(odDb::AssetRef::NULL_REF)
    , idleUWtoTread(odDb::AssetRef::NULL_REF)
    , swimToRun(odDb::AssetRef::NULL_REF)
    , slideSound(odDb::AssetRef::NULL_REF)
    , hardLandingSound(odDb::AssetRef::NULL_REF)
    , dragonCallSounds({})
    , huhSounds({})
    , cantReachSounds({})
    , cantUseSounds({})
    , fallIntoWaterSound(odDb::AssetRef::NULL_REF)
    , inventoryFullSound(odDb::AssetRef::NULL_REF)
    , noDartsSound(odDb::AssetRef::NULL_REF)
    , noArrowsSound(odDb::AssetRef::NULL_REF)
    , sheatheSound(odDb::AssetRef::NULL_REF)
    , pushObjectSounds({})
    , attackGrunts({})
    , getThePointSounds({})
    , getThePointSndChance(50)
    {
    }

    void HumanControlFields::probeFields(odRfl::FieldProbe &probe)
    {
        PlayerCommonFields::probeFields(probe);

        probe
            ("Character Channels")
               (rightWeaponChannel, "Right Weapon Channel")
               (leftWeaponChannel, "Left Weapon Channel")
               (torsoChannel, "Torso chan")
               (lowerBodyChan, "Lower Body chan")
               (rightArmChan, "Right Arm chan")
               (solveToChans, "Solve To Chans")
               (leftLegChans, "Left Leg Chans")
               (rightLegChans, "Right Leg Chans")
               (hair1Channel, "Hair1 Channel")
           ("General Motion Speeds")
               (multiplayerSpeedScaling, "Multiplayer Speed Scaling")
           ("Health And Damage")
               (fallStartDmgSpeed, "Fall Start Dmg Speed (lu/s)")
               (fallDeathSpeed, "Fall Death Speed (lu/s)")
           ("Death")
               (drown, "Drown")
               (drownSound, "Drown Sound")
           ("Movement With Weapons Animations")
               (combatIdleOneHand, "Combat Idle OneHand")
               (combatIdleTwoHand, "Combat Idle TwoHand")
               (walkOneHanded, "Walk OneHanded")
               (runOneHanded, "Run OneHanded")
               (strafeLeftOneHanded, "Strafe Left OneHanded")
               (strafeRightOneHanded, "Strafe Right OneHanded")
               (walkCombat, "Walk Combat")
               (runCombat, "Run Combat")
           ("Dragon Interaction")
               (rideAir, "Ride (Air)")
               (rideGround, "Ride (Ground)")
               (mount, "Mount")
               (dismount, "Dismount")
           ("Jump, Fall, And Land Animations")
               (jump, "Jump")
               (inAir, "In Air")
               (landing, "Landing")
               (landingSmall, "Landing Small")
               (landingRun, "Landing Run")
           ("Crouch Animations")
               (noncombatToCrouch, "Noncombat To Crouch")
               (combatToCrouch, "Combat To Crouch")
               (noncombatCrouched, "Noncombat Crouched")
               (combatCrouched, "Combat Crouched")
               (waddleForward, "Waddle Forward")
               (rollLeft, "Roll Left")
               (rollRight, "Roll Right")
               (rollForward, "Roll Forward")
               (rollBack, "Roll Back")
           ("Special Moves Animations")
               (cartwheelL, "Cartwheel L")
               (cartwheelR, "Cartwheel R")
               (flipForward, "Flip Forward")
               (flipBack, "Flip Back")
           ("Object Interaction Animations")
               (pushRollable, "Push Rollable")
               (pushSlidable, "Push Slidable")
               (ladderUp1, "Ladder Up 1")
               (ladderUp2, "Ladder Up 2")
               (ladderDown1, "Ladder Down 1")
               (ladderDown2, "Ladder Down 2")
               (ladderUpLIdle, "Ladder Up L Idle")
               (ladderUpRIdle, "Ladder Up R Idle")
               (ladderDownRIdle, "Ladder Down R Idle")
               (getOnLadderB, "Get On Ladder B")
               (getOffLadderB, "Get Off Ladder B")
               (getOnLadderT, "Get On Ladder T")
               (getOffLadderT, "Get Off Ladder T")
               (stairsUp, "Stairs Up")
               (stairsDown, "Stairs Down")
               (stairsUpIdleL, "Stairs Up Idle L")
               (stairsUpIdleR, "Stairs Up Idle R")
               (stairsDownIdleL, "Stairs Down Idle L")
               (stairsDownIdleR, "Stairs Down Idle R")
               (huh, "Huh?")
               (_180Turn, "180 Turn")
               (useMagicCrystal, "Use Magic Crystal")
           ("Environment Interaction Animations")
               (slideForward, "Slide Forward")
               (slideBackward, "Slide Backward")
               (balancing, "Balancing")
           ("Projectile Weapons")
               (throw, "Throw")
               (shootGun, "Shoot Gun")
               (reloadGun, "Reload Gun")
               (archerMedium, "Archer Medium")
               (archerLow, "Archer Low")
               (gunCamHorzDistance, "GunCam Horz Distance")
               (gunCamVertDistance, "GunCam Vert Distance")
           ("One Handed Attack Animations")
               (oneHandRH, "OneHand RH")
               (oneHandRM1, "OneHand RM1")
               (oneHandRM2, "OneHand RM2")
               (oneHandRM3, "OneHand RM3")
               (oneHandRL, "OneHand RL")
               (oneHandSH, "OneHand SH")
               (oneHandSM, "OneHand SM")
               (oneHandSL, "OneHand SL")
               (oneHandUB1, "OneHand UB1")
               (oneHandUB2, "OneHand UB2")
               (oneHandUB3, "OneHand UB3")
           ("Two Handed Attack Animations")
               (twoHandRH, "TwoHand RH")
               (twoHandRM1, "TwoHand RM1")
               (twoHandRM2, "TwoHand RM2")
               (twoHandRM3, "TwoHand RM3")
               (twoHandRL, "TwoHand RL")
               (twoHandSH, "TwoHand SH")
               (twoHandSM, "TwoHand SM")
               (twoHandSL, "TwoHand SL")
               (twoHandUB1, "TwoHand UB1")
               (twoHandUB2, "TwoHand UB2")
               (twoHandUB3, "TwoHand UB3")
           ("Special Magic Attack Animations")
               (fireSA, "Fire SA")
               (iceSA, "Ice SA")
               (lightningSA, "Lightning SA")
               (deathSA, "Death SA")
           ("Combo Attack Animations")
               (strafeAttackLUB, "Strafe Attack L UB")
               (strafeAttackRUB, "Strafe Attack R UB")
               (rollLAttack, "Roll L Attack")
               (rollRAttack, "Roll R Attack")
               (specialAttackThrust, "Special Attack Thrust")
               (specialAttackLeft, "Special Attack Left")
               (specialAttackRight, "Special Attack Right")
               (specialAttackSpin, "Special Attack Spin")
               (specialAttackSwing180, "Special Attack Swing 180")
               (specialAttackJump, "Special Attack Jump")
           ("Special Attack Damage")
               (saThrustDamageMultiplier, "SA Thrust Damage Multiplier")
               (saLeftDamageMultiplier, "SA Left Damage Multiplier")
               (saRightDamageMultiplier, "SA Right Damage Multiplier")
               (saSpinDamageMultiplier, "SA Spin Damage Multiplier")
               (saSwing180DamageMultiplier, "SA Swing 180 Damage Multiplier")
               (saJumpDamageMultiplier, "SA Jump Damage Multiplier")
           ("Defense")
               (block, "Block")
               (crouchedBlock, "Crouched Block")
               (blockDamageReductionPercent, "Block Damage Reduction %")
           ("Sheathe and Unsheathe")
               (sheathe, "Sheathe")
               (unsheathe, "Unsheathe")
           ("Attack Factors")
               (reAttackWindow, "Re-attack Window (s)")
           ("Damage Reaction Animations") // prime example that field names are not unique
               (hitRxnHSLAnim, "HitRxn HSL")
               (hitRxnHSHAnim, "HitRxn HSH")
               (hitRxnOSLAnim, "HitRxn OSL")
               (hitRxnOSHAnim, "HitRxn OSH")
               (hitRxnFSLAnim, "HitRxn FSL")
               (hitRxnFSHAnim, "HitRxn FSH")
           ("Damage Reaction Sounds")
               (hitRxnHSLSound, "HitRxn HSL")
               (hitRxnHSHSound, "HitRxn HSH")
               (hitRxnOSLSound, "HitRxn OSL")
               (hitRxnOSHSound, "HitRxn OSH")
               (hitRxnFSLSound, "HitRxn FSL")
               (hitRxnFSHSound, "HitRxn FSH")
           ("Ground Motion Animations")
               (walkStrafeL, "Walk Strafe L")
               (walkStrafeR, "Walk Strafe R")
               (slowWalk, "Slow Walk")
               (runBackwards, "Run Backwards")
               (runBackwardsOneHanded, "Run Backwards One Handed")
               (noncombat2Run, "Noncombat2Run")
               (run2Ready, "Run2Ready")
               (run2ReadyL, "Run2ReadyL")
               (walk2Ready, "Walk2Ready")
               (strafeL2Ready, "StrafeL2Ready")
               (strafeR2Ready, "StrafeR2Ready")
               (turnLeft, "Turn Left")
               (turnRight, "Turn Right")
               (bumpIntoWall, "Bump Into Wall")
           ("Swimming and Water Motion")
               (swimForwardSpeed, "Swim Forward Speed")
               (swimBackwardSpeed, "Swim Backward Speed")
               (airConsumptionRate, "Air Consumption Rate (%/sec)")
               (airReplenishmentRate, "Air Replenishment Rate (%/sec)")
               (inAirToSwanDive, "InAir To Swan Dive")
               (swanDive, "Swan Dive")
               (swim, "Swim")
               (backswim, "Backswim")
               (swimToBackswim, "Swim To Backswim")
               (backswimToSwim, "Backswim To Swim")
               (treadWater, "Tread Water")
               (idleUnderwater, "Idle Underwater")
               (idleUWtoTread, "IdleUW to Tread")
               (swimToRun, "Swim To Run")
           ("Human Sounds")
               (slideSound, "Slide Sound (looped)")
               (hardLandingSound, "Hard Landing Sound")
               (dragonCallSounds, "Dragon Call Sound")
               (huhSounds, "Huh? Sound")
               (cantReachSounds, "Can't Reach Sound")
               (cantUseSounds, "Can't Use Sound")
               (fallIntoWaterSound, "Fall Into Water Sound")
               (inventoryFullSound, "Inventory Full Sound")
               (noDartsSound, "No Darts Sound")
               (noArrowsSound, "No Arrows Sound")
               (sheatheSound, "Sheathe Sound")
               (pushObjectSounds, "Push Object Sounds")
               (attackGrunts, "Attack Grunts")
           ("Ambient Comments")
               (getThePointSounds, "Get-the-point Sounds")
               (getThePointSndChance, "Get the point Snd Chance (0-100)");
    }

}
